### ISSUE TITLE
Se debe usar printf para escribir a stdout

### ISSUE THREAD

**Issue by navarroaxel** [abelFariasJuarez/TP-0#1]
Reemplazar

``` C
puts("...");
```

por

``` C
printf("...");
```

**Comment by abelFariasJuarez** [comment]
Axel buenas noches,
Muchas gracias por la observación, me podrías dar una justificación?
Un cordial saludo.
Abel Farias Juarez

**Comment by navarroaxel** [comment]
Hola Abel, aunque puts y printf tienen resultados parecidos en la mayoría de los casos la cátedra incentiva el uso de printf, más que nada por formateos de variables ("%s") y no agrega un "\n" automático al final de la string.

Para los fines de este TP no es el igual comportamiento lo que importa, sino el consenso de que todos usemos printf en este curso.

Más info en http://www.dummies.com/how-to/content/how-to-display-text-onscreen-in-c-with-puts-and-pr.html

Saludos!
AN

**Comment by abelFariasJuarez** [comment]
​Axel, buenas noches,
Listo!.
Muchas gracias.
Un cordial saludo.
Abel Farias Juarez

​

**Comment by navarroaxel** [comment]
Buenísimo Abel, cerra/resolve los issues resueltos (q en este caso son ambos).
